### ISSUE TITLE
Refactor to separate essential from test code

### ISSUE THREAD

**Issue by kevinsullivan** [kevinsullivan/phys#1]
1. create a new feature branch, refactor_test_code
2. create file PhysL_test.clean
3. Move all the test out of PhysL.lean and into the test file
4. Let know when done we'll review and merge into the master branch

**Comment by arh4uwe** [comment]
Closing an issue means that it's solved, right?

Anyway, I did what you told me to do. I also fixed a weird error in the function `scalar_eval` where it didn't recognize the constructor `scalar_var`. For some reason, it only recognized it if I typed `scalar_expression.scalar_var`.

**Comment by kevinsullivan** [comment]
Good job, Amanda. Ben or Andrew can help you through the process of merging
your changes into our master branch. Again, welcome aboard! --Kevin
